1.4.0 - ready for docker image on gcr.io

diff --git a/ezai-docker b/ezai-docker
--- a/ezai-docker
+++ b/ezai-docker
@@ -1,6 +1,49 @@
 #!/usr/bin/env bash
 
-run () {
+ezai_build_image() {
+
+source .env
+
+  dfile="Dockerfile"
+  dfolder="."
+
+  if [ "$(docker image inspect $iname:$itag > /dev/null 2>&1 && echo 1 || echo '')" ];
+  then
+    echo "found image $iname:$itag.. rebuilding"
+  else
+    echo "creating image $iname:$itag"
+  fi
+
+  if [ $compute = "gpu" ];
+  then
+    base="nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04"
+  else
+    base="ubuntu:18.04"
+  fi
+  barg=" --build-arg BASE=$base "
+  barg+=" --build-arg COMPUTE=$compute "
+  bopt=" "
+#  bopt+=" --no-cache "
+#  barg+=" --build-arg AI_UID=${AI_UID} "
+#  barg+=" --build-arg AI_GID=${AI_GID} "
+#  barg+=" --build-arg AI_UNAME=${AI_UNAME} "
+  docker build $bopt -t $iname:$itag $barg -f $dfile $dfolder
+
+  # HAVE TO CHECK FOR IMAGE AGAIN BECAUSE BULD FAILS SOMETIME
+  if [ "$(docker image inspect $iname:$itag > /dev/null 2>&1 && echo 1 || echo '')" ];
+  then
+     echo "created image $iname:$itag"
+  else
+     echo "not created image $iname:$itag"
+  fi
+}
+
+ezai_pull_image() {
+    echo "pulling image $iname:$itag"
+    docker pull ghcr.io/armando-fndango/$iname:$itag
+}
+
+ezai_runc () {
     # TODO: instead of root, run as user
   # docker run -it --gpus all --name phd-gpu-1 -v ${HOME}/datasets:/root/datasets -v /home/armando/phd:/root/phd
 
@@ -11,37 +54,23 @@ run () {
 
   source .env
 
-  dfile="Dockerfile"
-  dfolder="."
+  #dfile="Dockerfile"
+  #dfolder="."
 
   # exec options
   evars=" -e COMPUTE=${compute} -e PROJECT=${project} -e DISPLAY -e XAUTHORITY -e NVIDIA_DRIVER_CAPABILITIES=all "
   user="-u ${AI_UID}:${AI_GID}"
   xhost +  # for running GUI app in container
 
-  if [ "$(docker image inspect $iname:latest > /dev/null 2>&1 && echo 1 || echo '')" ];
+  if [ "$(docker image inspect $iname:$itag > /dev/null 2>&1 && echo 1 || echo '')" ];
   then
-    echo "found image $iname"
+    echo "found image $iname:$itag"
   else
-    echo "creating image $iname"
-    if [ $compute = "gpu" ];
-    then
-      base="nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04"
-    else
-      base="ubuntu:18.04"
-    fi
-    barg=" --build-arg BASE=$base "
-    barg+=" --build-arg COMPUTE=$compute "
-    bopt=" "
-  #  bopt+=" --no-cache "
-  #  barg+=" --build-arg AI_UID=${AI_UID} "
-  #  barg+=" --build-arg AI_GID=${AI_GID} "
-  #  barg+=" --build-arg AI_UNAME=${AI_UNAME} "
-    docker build $bopt -t $iname $barg -f $dfile $dfolder
+    ezai_pull_image
   fi
 
   # HAVE TO CHECK FOR IMAGE AGAIN BECAUSE BULD FAILS SOMETIME
-  if [ "$(docker image inspect $iname:latest > /dev/null 2>&1 && echo 1 || echo '')" ];
+  if [ "$(docker image inspect $iname:$itag > /dev/null 2>&1 && echo 1 || echo '')" ];
   then
     if [ "$(docker ps -q -f name=$cname -f status=exited)" ];
     then
@@ -57,23 +86,23 @@ run () {
       echo "creating, starting and then entering container $cname"
       # shellcheck disable=SC2154
       docker run -it --gpus all --name $cname \
-        "$user" "$wfolder" "$evars" $vfolders $cports $iname bash
+        $user $wfolder $evars $vfolders $cports $iname:$itag bash
     fi
   else
-     echo "not created image $iname"
+     echo "not pulled image $iname:$itag"
   fi
 
 }
 
-rmi () {
+ezai_rmi () {
   # remove the docker image
 
   source .env
 
-  docker rmi $iname --no-prune
+  docker rmi $iname:$itag --no-prune
 }
 
-rmc () {
+ezai_rmc () {
   # stop and remove the docker container
 
   source .env
